-- MySQL Script generated by MySQL Workbench
-- Wed Jul 12 16:11:11 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbinfox
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbinfox
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbinfox` DEFAULT CHARACTER SET utf8 ;
USE `dbinfox` ;

-- -----------------------------------------------------
-- Table `dbinfox`.`tbclientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinfox`.`tbclientes` (
  `idtcli` INT NOT NULL AUTO_INCREMENT,
  `nomecli` VARCHAR(50) NOT NULL,
  `fonecli` VARCHAR(50) NOT NULL,
  `emailcli` VARCHAR(50) NULL,
  PRIMARY KEY (`idtcli`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbinfox`.`tbusuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinfox`.`tbusuarios` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(50) NOT NULL,
  `fone` VARCHAR(15) NULL,
  `login` VARCHAR(15) NOT NULL,
  `senha` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbinfox`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinfox`.`estado` (
  `idestado` INT NOT NULL AUTO_INCREMENT,
  `nome_estado` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idestado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbinfox`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinfox`.`cidade` (
  `idcidade` INT NOT NULL AUTO_INCREMENT,
  `nome_cidade` VARCHAR(255) NOT NULL,
  `idestado` INT NOT NULL,
  PRIMARY KEY (`idcidade`),
  INDEX `fk_cidade_estado1_idx` (`idestado` ASC) VISIBLE,
  CONSTRAINT `fk_cidade_estado1`
    FOREIGN KEY (`idestado`)
    REFERENCES `dbinfox`.`estado` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbinfox`.`bairro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinfox`.`bairro` (
  `idbairro` INT NOT NULL AUTO_INCREMENT,
  `nome_bairro` VARCHAR(255) NOT NULL,
  `idcidade` INT NOT NULL,
  PRIMARY KEY (`idbairro`),
  INDEX `fk_bairro_cidade1_idx` (`idcidade` ASC) VISIBLE,
  CONSTRAINT `fk_bairro_cidade1`
    FOREIGN KEY (`idcidade`)
    REFERENCES `dbinfox`.`cidade` (`idcidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbinfox`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinfox`.`endereco` (
  `idendereco` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(255) NULL,
  `numero_endereco` VARCHAR(10) NULL,
  `complemento` VARCHAR(55) NULL,
  `iduser` INT NULL,
  `idbairro` INT NOT NULL,
  `idcli` INT NULL,
  PRIMARY KEY (`idendereco`),
  INDEX `fk_endereco_tbusuarios_idx` (`iduser` ASC) VISIBLE,
  INDEX `fk_endereco_bairro1_idx` (`idbairro` ASC) VISIBLE,
  INDEX `fk_endereco_tbclientes1_idx` (`idcli` ASC) VISIBLE,
  CONSTRAINT `fk_endereco_tbusuarios`
    FOREIGN KEY (`iduser`)
    REFERENCES `dbinfox`.`tbusuarios` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_bairro1`
    FOREIGN KEY (`idbairro`)
    REFERENCES `dbinfox`.`bairro` (`idbairro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_tbclientes1`
    FOREIGN KEY (`idcli`)
    REFERENCES `dbinfox`.`tbclientes` (`idtcli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbinfox`.`tbos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinfox`.`tbos` (
  `os` INT NOT NULL AUTO_INCREMENT,
  `data_os` TIMESTAMP NULL DEFAULT current_timestamp,
  `equipamento` VARCHAR(150) NULL,
  `defeito` VARCHAR(150) NOT NULL,
  `servico` VARCHAR(150) NULL,
  `tecnico` VARCHAR(50) NULL,
  `valor` DECIMAL(10,2) NULL,
  `idcli` INT NOT NULL,
  PRIMARY KEY (`os`),
  INDEX `fk_tbos_tbclientes1_idx` (`idcli` ASC) VISIBLE,
  CONSTRAINT `fk_tbos_tbclientes1`
    FOREIGN KEY (`idcli`)
    REFERENCES `dbinfox`.`tbclientes` (`idtcli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
